[workspace]
resolver = "2"
members = ["daemon", "tui"]

[workspace.dependencies]
tonic = "0.13.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
git2 = "0.20.1"
